#+test
package test_darwinkit

@require import "../darwinkit/AVFoundation"
@require import "../darwinkit/AppKit"
@require import "../darwinkit/AudioToolbox"
// @require import "../darwinkit/CloudKit"
@require import "../darwinkit/CoreAudio"
@require import "../darwinkit/CoreFoundation"
@require import "../darwinkit/CoreGraphics"
// @require import "../darwinkit/CoreHaptics"
@require import "../darwinkit/CoreMedia"
@require import "../darwinkit/CoreText"
@require import "../darwinkit/DiskArbitration"
@require import "../darwinkit/FSEvents"
@require import "../darwinkit/Foundation"
@require import "../darwinkit/GameController"
// @require import "../darwinkit/GameKit"
@require import "../darwinkit/IOKit"
@require import "../darwinkit/LocalAuthentication"
@require import "../darwinkit/Metal"
@require import "../darwinkit/MetalFX"
@require import "../darwinkit/MetalKit"
@require import "../darwinkit/ModelIO"
@require import "../darwinkit/QuartzCore"
@require import "../darwinkit/Security"
// @require import "../darwinkit/UIKit"
