#!/usr/bin/env bash
set -eo pipefail
_script_dir=$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )
cd "${_script_dir}"

frameworks=()
use_ios=
lite=
cgen_args=()

while true; do
  case $1 in
    -i|-ios)
      use_ios=1
    ;;
    -l|-lite)
      echo "Lite mode not supported anymore"
      exit 1
    ;;
    -m|-markers)
      cgen_args+=("--odin-emit-text-markers")
    ;;
    -v|-verbose|--verbose)
      cgen_args+=("-v")
    ;;
    *)
      frameworks+=($1)
    ;;
  esac
  shift || break
done

if [[ 0 -eq ${#frameworks[@]} ]]; then
  echo "Error: No frameworks specified."
  exit 1
fi

source ./config

out_folder=$(darwodin_get_output_folder "${use_ios}" "${lite}")
appkit=AppKit

if [[ ${lite} -eq 1 ]]; then
  cgen_args+=(--odin-elaborated-objc-classes ../lite-classes)
fi

if [[ ${use_ios} -eq 1 ]]; then
  appkit=UIKit

  # Change externals lookup and export location for iOS
  src_exports_dir="${_script_dir}/exports"
  ios_exports_dir="${_script_dir}/exports_ios"

  cgen_args+=(
    --odin-export-types-path
    "$ios_exports_dir"
    --odin-external-file-map
    "${src_exports_dir}/AppKit.exports.yml=${ios_exports_dir}/Foundation.exports.yml,${ios_exports_dir}/UIKit.exports.yml"
    --odin-external-dir-map
    "${src_exports_dir}=${ios_exports_dir}"
    --odin-no-re-exports
    Foundation
  )
fi


out_path=../${out_folder}
for f in ${frameworks[@]}; do
    f=$(darwodin_filter_framework $f $use_ios)
    echo "$f"

    framework_lower="$(echo $f | tr '[:upper:]' '[:lower:]')"

    framework_cfg="configs/${framework_lower}.yml"
    if [[ -e "configs/${framework_lower}.toml" ]]; then
      framework_cfg="configs/${framework_lower}.toml"
    fi

    # Check ios-specific version
    if [[ ${use_ios} -eq 1 ]]; then
      framework_cfg_ios_toml="configs/${framework_lower}_ios.toml"
      framework_cfg_ios_yaml="configs/${framework_lower}_ios.yml"

      if [[ -e "${framework_cfg_ios_toml}" ]]; then
        framework_cfg=$framework_cfg_ios_toml
      elif [[ -e "${framework_cfg_ios_yaml}" ]]; then
        framework_cfg=$framework_cfg_ios_yaml
      fi
    fi

    args=()
    if [[ ${use_ios} -eq 1 ]]; then
      args=(--def definitions/ios/${framework_lower}.json)
    fi

    # Test generics
    # args+=(--odin-objc-generics)

    args+=(
      --odin-no-canon-link-path
    )

    # echo "${out_path}"
    csgen ${cgen_args[@]} ${args[@]} --odin-out "${out_path}" "$framework_cfg"
done


# Copy Objective-C sources
# # if [[ "${use_ios}" -eq 1 ]] || [[ "${lite}" -eq 1 ]]; then
#   if [[ ! -h "${out_folder}/darwodin/ObjectiveC" ]]; then
#     # ln -s "$(pwd)/ObjectiveC" "$(pwd)/${out_folder}/darwodin/ObjectiveC"
#     cp -r "ObjectiveC" "${out_folder}/darwodin/ObjectiveC"
#   fi
# fi
