#!/usr/bin/env bash
set -eo pipefail
cd $( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )

extra_args=()
while true; do
  case $1 in
    -m|-markers)
      extra_args+=(-m)
    ;;
    -v|-verbose|--verbose)
      extra_args+=(-v)
    ;;
  esac
  shift || break
done

echo "=== Binding macOS ==="
./bind-all ${extra_args[@]}

# echo ""
# echo "=== Binding macOS Lite ==="
# ./bind-all -lite

echo ""
echo "=== Binding iOS ==="
./bind-all -ios "${extra_args[@]}"

