#!/usr/bin/env bash
set -eo pipefail
cd $( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )

use_ios=
lite=

while true; do
  case $1 in
    -ios)
      use_ios=1
    ;;
    -l)
      lite=1
    ;;
    -lite)
      lite=1
    ;;
  esac
  shift || break
done

source ./config

frameworks=(
    ${darwodin_base_frameworks[@]}
)


ios_arg=
if [[ ${use_ios} -ne 1 ]]; then
    frameworks+=(${darwodin_macos_frameworks[@]})
else
    frameworks+=(${darwodin_ios_frameworks[@]})
    ios_arg=-ios
fi

if [[ ${lite} -eq 1 ]]; then
    lite_arg="-l"
fi

./bind ${frameworks[@]} ${lite_arg} ${ios_arg}


# Copy Objective-C package
out_dir=$(darwodin_get_output_folder "${use_ios}" "${lite}")

cp -r ./ObjectiveC "$out_dir/darwodin/ObjectiveC"


# Create dummy packaged for frameworks not in the target sdk
excluded_frameworks=

if [[ ${use_ios} -ne 1 ]]; then
    excluded_frameworks=(${darwodin_ios_frameworks[@]})
else
    excluded_frameworks=(${darwodin_macos_frameworks[@]})
fi

for f in ${excluded_frameworks[@]}; do
    mkdir -p "${out_dir}/darwodin/$f/"
    echo "package $f" > "${out_dir}/darwodin/$f/${f}.odin"
done
