#!/usr/bin/env bash
set -eo pipefail

_dir="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"
cd "${_dir}"

# Usage check [<targets>]

source ./config

targets=()
merged=false
args=()
is_ios=false
check_enums=false # Check which enums can be bit_sets

while (( $# > 0 )); do
  case $1 in

    -ios|--ios|-i)
      is_ios=true
      args+=(
        -target:darwin_arm64 
        -subtarget:iphone
      )
      ;;

    -m|-merged|--merged)
      merged=true
      ;;

    -e|-enums|--enums)
      echo "Checking enums that can be bit_sets"
      echo ""
      check_enums=true
      ;;

    *)
      targets+=($1)
      ;;
  esac

  shift || break
done

# Set default target framework
if [[ ${#targets[@]} -eq 0 ]]; then
  targets=("${darwodin_base_frameworks[@]}")
fi


frameworks_path="darwodin-macos/darwodin"

if $is_ios; then
  frameworks_path="darwodin-ios/darwodin"
  echo "Checking iOS"
  if ! $merged ; then
    echo ""
  fi
fi

if $merged ; then
  frameworks_path="darwinkit"
  echo "Checking merged"
  echo ""
fi


for t in ${targets[@]}; do
  echo "${t}"

  if $check_enums; then
    ios_param=
    if $is_ios; then
      ios_param=1
    fi

    t="${t,,}"  # Lower case

    cfg_path="configs/${t}.yml"
    if [[ -e "configs/${t}.toml" ]]; then
      cfg_path="configs/${t}.toml"
    fi
  
    csgen --odin-check-enums "$cfg_path"
    echo ""
  else
    odin check "${frameworks_path}/${t}" ${args[@]} -no-entry-point
  fi
done
