#!/usr/bin/env bash
set -eo pipefail
cd $( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )

source ./config

macos_frameworks=(
    ${darwodin_base_frameworks[@]}
    ${darwodin_macos_frameworks[@]}
)

ios_frameworks=(
    ${darwodin_base_frameworks[@]}
    ${darwodin_ios_frameworks[@]}
)

# MacOS
echo "Generating macOS definitions..."
for f in ${macos_frameworks[@]}; do

    include=$(darwodin_get_header_for_framework $f)
        
    flist=($(echo "$f" | tr ',' ' '))
    for ((i=0; i < ${#flist[@]}; i++ )); do
        flist[$i]="-f ${flist[$i]} -i $include"
    done
    ./gen-def ${flist[@]}
done

# iOS
echo ""
echo "Generating iOS definitions..."
for f in ${ios_frameworks[@]}; do

    include=$(darwodin_get_header_for_framework $f)

    flist=($(echo "$f" | tr ',' ' '))
    for ((i=0; i < ${#flist[@]}; i++ )); do
        flist[$i]="-f ${flist[$i]} -i $include"
    done

    ./gen-def -ios ${flist[@]}
done

