#!/usr/bin/env bash
set -eo pipefail
cd $( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )

source ./config

# Copy Objective-C package
out_dir=$(darwodin_get_output_folder 0 0)
rsync -rah ./ObjectiveC "$out_dir/darwodin/"

out_dir=$(darwodin_get_output_folder 0 1)
rsync -rah ./ObjectiveC "$out_dir/darwodin/"

out_dir=$(darwodin_get_output_folder 1 0)
rsync -rah ./ObjectiveC "$out_dir/darwodin/"

out_dir=$(darwodin_get_output_folder 1 1)
rsync -rah ./ObjectiveC "$out_dir/darwodin/"

