#!/usr/bin/env bash
set -eo pipefail
cd $( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )

source ./config

# Copy Objective-C package
# out_dir=$(darwodin_get_output_folder 0 0)
# rsync -rah ./ObjectiveC "$out_dir/darwodin/"

# out_dir=$(darwodin_get_output_folder 0 1)
# rsync -rah ./ObjectiveC "$out_dir/darwodin/"

# out_dir=$(darwodin_get_output_folder 1 0)
# rsync -rah ./ObjectiveC "$out_dir/darwodin/"

# out_dir=$(darwodin_get_output_folder 1 1)
# rsync -rah ./ObjectiveC "$out_dir/darwodin/"


set +e
darwodin_variants=(
    $(darwodin_get_output_folder 0 0)
    $(darwodin_get_output_folder 0 1)
    $(darwodin_get_output_folder 1 0)
    $(darwodin_get_output_folder 1 1)
)

for folder in ${darwodin_variants[@]}; do
    echo $folder
    pushd "${folder}/darwodin" >/dev/null
    set +e
    ln -s ../../ObjectiveC ObjectiveC
    ln -s ../../mach mach
    ln -s ../../libc libc
    set -e
    popd >/dev/null
done
