#! /usr/bin/env bash
set -eo pipefail
cd $( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )

subtarget=()
while (($#)); do
  case $1 in
    -ios)
        echo "iOS"
        subtarget=(-subtarget:iphone)
        ;;
    *)
      echo "Unknown argument specified '${1}'"
      exit 1
        ;;
  esac

  shift
done


set -x
odin build . \
"-collection:darwinkit=/Users/harito/projects/apps/odin-libs/.repos/darwodin/darwinkit" \
-all-packages \
-target:darwin_arm64 \
-build-mode:test \
-out:./.bin/test_merged \
${subtarget[@]}
