package darwodin_AudioToolbox

import "base:intrinsics"
import "base:runtime"
import cffi "core:c"
import ObjC "../ObjectiveC"
import mach "../mach"
import CF "../CoreFoundation"
import CA "../CoreAudio"
import CM "../CoreMedia"
import NS "../Foundation"


/// Structs
ValueRange                :: CA.ValueRange
ValueTranslation          :: CA.ValueTranslation
Buffer                    :: CA.Buffer
BufferList                :: CA.BufferList
StreamBasicDescription    :: CA.StreamBasicDescription
StreamPacketDescription   :: CA.StreamPacketDescription
SMPTETime                 :: CA.SMPTETime
TimeStamp                 :: CA.TimeStamp
ClassDescription          :: CA.ClassDescription
ChannelDescription        :: CA.ChannelDescription
ChannelLayout             :: CA.ChannelLayout
FormatListItem            :: CA.FormatListItem
ObjectPropertyAddress     :: CA.ObjectPropertyAddress
StreamRangedDescription   :: CA.StreamRangedDescription
HardwareIOProcStreamUsage :: CA.HardwareIOProcStreamUsage

/// Typedefs
SampleType                   :: CA.SampleType
UnitSampleType               :: CA.UnitSampleType
FormatID                     :: CA.FormatID
FormatFlags                  :: CA.FormatFlags
ChannelLabel                 :: CA.ChannelLabel
ChannelLayoutTag             :: CA.ChannelLayoutTag
SessionID                    :: CA.SessionID
ObjectID                     :: CA.ObjectID
ClassID                      :: CA.ClassID
ObjectPropertySelector       :: CA.ObjectPropertySelector
ObjectPropertyScope          :: CA.ObjectPropertyScope
ObjectPropertyElement        :: CA.ObjectPropertyElement
ObjectPropertyListenerProc   :: CA.ObjectPropertyListenerProc
ObjectPropertyListenerBlock  :: CA.ObjectPropertyListenerBlock
DeviceIOProc                 :: CA.DeviceIOProc
DeviceIOBlock                :: CA.DeviceIOBlock
DeviceIOProcID               :: CA.DeviceIOProcID
HardwarePropertyID           :: CA.HardwarePropertyID
HardwarePropertyListenerProc :: CA.HardwarePropertyListenerProc
DeviceID                     :: CA.DeviceID
DevicePropertyID             :: CA.DevicePropertyID
DevicePropertyListenerProc   :: CA.DevicePropertyListenerProc
StreamID                     :: CA.StreamID
StreamPropertyListenerProc   :: CA.StreamPropertyListenerProc

/// Enums
SMPTETimeType                :: CA.SMPTETimeType
SMPTETimeFlags               :: CA.SMPTETimeFlags
TimeStampFlags               :: CA.TimeStampFlags
ChannelBitmap                :: CA.ChannelBitmap
ChannelFlags                 :: CA.ChannelFlags
ChannelCoordinateIndex       :: CA.ChannelCoordinateIndex
HardwarePowerHint            :: CA.HardwarePowerHint
LevelControlTransferFunction :: CA.LevelControlTransferFunction

/// Functions
ObjectShow                        :: CA.ObjectShow
ObjectHasProperty                 :: CA.ObjectHasProperty
ObjectIsPropertySettable          :: CA.ObjectIsPropertySettable
ObjectGetPropertyDataSize         :: CA.ObjectGetPropertyDataSize
ObjectGetPropertyData             :: CA.ObjectGetPropertyData
ObjectSetPropertyData             :: CA.ObjectSetPropertyData
ObjectAddPropertyListener         :: CA.ObjectAddPropertyListener
ObjectRemovePropertyListener      :: CA.ObjectRemovePropertyListener
ObjectAddPropertyListenerBlock    :: CA.ObjectAddPropertyListenerBlock
ObjectRemovePropertyListenerBlock :: CA.ObjectRemovePropertyListenerBlock
HardwareUnload                    :: CA.HardwareUnload
HardwareCreateAggregateDevice     :: CA.HardwareCreateAggregateDevice
HardwareDestroyAggregateDevice    :: CA.HardwareDestroyAggregateDevice
DeviceCreateIOProcID              :: CA.DeviceCreateIOProcID
DeviceCreateIOProcIDWithBlock     :: CA.DeviceCreateIOProcIDWithBlock
DeviceDestroyIOProcID             :: CA.DeviceDestroyIOProcID
DeviceStart                       :: CA.DeviceStart
DeviceStartAtTime                 :: CA.DeviceStartAtTime
DeviceStop                        :: CA.DeviceStop
DeviceGetCurrentTime              :: CA.DeviceGetCurrentTime
DeviceTranslateTime               :: CA.DeviceTranslateTime
DeviceGetNearestStartTime         :: CA.DeviceGetNearestStartTime
HardwareAddRunLoopSource          :: CA.HardwareAddRunLoopSource
HardwareRemoveRunLoopSource       :: CA.HardwareRemoveRunLoopSource
HardwareGetPropertyInfo           :: CA.HardwareGetPropertyInfo
HardwareGetProperty               :: CA.HardwareGetProperty
HardwareSetProperty               :: CA.HardwareSetProperty
HardwareAddPropertyListener       :: CA.HardwareAddPropertyListener
HardwareRemovePropertyListener    :: CA.HardwareRemovePropertyListener
DeviceAddIOProc                   :: CA.DeviceAddIOProc
DeviceRemoveIOProc                :: CA.DeviceRemoveIOProc
DeviceRead                        :: CA.DeviceRead
DeviceGetPropertyInfo             :: CA.DeviceGetPropertyInfo
DeviceGetProperty                 :: CA.DeviceGetProperty
DeviceSetProperty                 :: CA.DeviceSetProperty
DeviceAddPropertyListener         :: CA.DeviceAddPropertyListener
DeviceRemovePropertyListener      :: CA.DeviceRemovePropertyListener
StreamGetPropertyInfo             :: CA.StreamGetPropertyInfo
StreamGetProperty                 :: CA.StreamGetProperty
StreamSetProperty                 :: CA.StreamSetProperty
StreamAddPropertyListener         :: CA.StreamAddPropertyListener
StreamRemovePropertyListener      :: CA.StreamRemovePropertyListener
GetCurrentHostTime                :: CA.GetCurrentHostTime
GetHostClockFrequency             :: CA.GetHostClockFrequency
GetHostClockMinimumTimeDelta      :: CA.GetHostClockMinimumTimeDelta
ConvertHostTimeToNanos            :: CA.ConvertHostTimeToNanos
ConvertNanosToHostTime            :: CA.ConvertNanosToHostTime

/// Consts
k_NoError                                                        :: CA.k_NoError
k_UnimplementedError                                             :: CA.k_UnimplementedError
k_FileNotFoundError                                              :: CA.k_FileNotFoundError
k_FilePermissionError                                            :: CA.k_FilePermissionError
k_TooManyFilesOpenError                                          :: CA.k_TooManyFilesOpenError
k_BadFilePathError                                               :: CA.k_BadFilePathError
k_ParamError                                                     :: CA.k_ParamError
k_MemFullError                                                   :: CA.k_MemFullError
kFormatLinearPCM                                                 :: CA.kFormatLinearPCM
kFormatAC3                                                       :: CA.kFormatAC3
kFormat60958AC3                                                  :: CA.kFormat60958AC3
kFormatAppleIMA4                                                 :: CA.kFormatAppleIMA4
kFormatMPEG4AAC                                                  :: CA.kFormatMPEG4AAC
kFormatMPEG4CELP                                                 :: CA.kFormatMPEG4CELP
kFormatMPEG4HVXC                                                 :: CA.kFormatMPEG4HVXC
kFormatMPEG4TwinVQ                                               :: CA.kFormatMPEG4TwinVQ
kFormatMACE3                                                     :: CA.kFormatMACE3
kFormatMACE6                                                     :: CA.kFormatMACE6
kFormatULaw                                                      :: CA.kFormatULaw
kFormatALaw                                                      :: CA.kFormatALaw
kFormatQDesign                                                   :: CA.kFormatQDesign
kFormatQDesign2                                                  :: CA.kFormatQDesign2
kFormatQUALCOMM                                                  :: CA.kFormatQUALCOMM
kFormatMPEGLayer1                                                :: CA.kFormatMPEGLayer1
kFormatMPEGLayer2                                                :: CA.kFormatMPEGLayer2
kFormatMPEGLayer3                                                :: CA.kFormatMPEGLayer3
kFormatTimeCode                                                  :: CA.kFormatTimeCode
kFormatMIDIStream                                                :: CA.kFormatMIDIStream
kFormatParameterValueStream                                      :: CA.kFormatParameterValueStream
kFormatAppleLossless                                             :: CA.kFormatAppleLossless
kFormatMPEG4AAC_HE                                               :: CA.kFormatMPEG4AAC_HE
kFormatMPEG4AAC_LD                                               :: CA.kFormatMPEG4AAC_LD
kFormatMPEG4AAC_ELD                                              :: CA.kFormatMPEG4AAC_ELD
kFormatMPEG4AAC_ELD_SBR                                          :: CA.kFormatMPEG4AAC_ELD_SBR
kFormatMPEG4AAC_ELD_V2                                           :: CA.kFormatMPEG4AAC_ELD_V2
kFormatMPEG4AAC_HE_V2                                            :: CA.kFormatMPEG4AAC_HE_V2
kFormatMPEG4AAC_Spatial                                          :: CA.kFormatMPEG4AAC_Spatial
kFormatMPEGD_USAC                                                :: CA.kFormatMPEGD_USAC
kFormatAMR                                                       :: CA.kFormatAMR
kFormatAMR_WB                                                    :: CA.kFormatAMR_WB
kFormatAudible                                                   :: CA.kFormatAudible
kFormatiLBC                                                      :: CA.kFormatiLBC
kFormatDVIIntelIMA                                               :: CA.kFormatDVIIntelIMA
kFormatMicrosoftGSM                                              :: CA.kFormatMicrosoftGSM
kFormatAES3                                                      :: CA.kFormatAES3
kFormatEnhancedAC3                                               :: CA.kFormatEnhancedAC3
kFormatFLAC                                                      :: CA.kFormatFLAC
kFormatOpus                                                      :: CA.kFormatOpus
kFormatAPAC                                                      :: CA.kFormatAPAC
kFormatFlagIsFloat                                               :: CA.kFormatFlagIsFloat
kFormatFlagIsBigEndian                                           :: CA.kFormatFlagIsBigEndian
kFormatFlagIsSignedInteger                                       :: CA.kFormatFlagIsSignedInteger
kFormatFlagIsPacked                                              :: CA.kFormatFlagIsPacked
kFormatFlagIsAlignedHigh                                         :: CA.kFormatFlagIsAlignedHigh
kFormatFlagIsNonInterleaved                                      :: CA.kFormatFlagIsNonInterleaved
kFormatFlagIsNonMixable                                          :: CA.kFormatFlagIsNonMixable
kFormatFlagsAreAllClear                                          :: CA.kFormatFlagsAreAllClear
kFormatFlagsNativeEndian                                         :: CA.kFormatFlagsNativeEndian
kFormatFlagsCanonical                                            :: CA.kFormatFlagsCanonical
kFormatFlagsAudioUnitCanonical                                   :: CA.kFormatFlagsAudioUnitCanonical
kFormatFlagsNativeFloatPacked                                    :: CA.kFormatFlagsNativeFloatPacked
kChannelLabel_Unknown                                            :: CA.kChannelLabel_Unknown
kChannelLabel_Unused                                             :: CA.kChannelLabel_Unused
kChannelLabel_UseCoordinates                                     :: CA.kChannelLabel_UseCoordinates
kChannelLabel_Left                                               :: CA.kChannelLabel_Left
kChannelLabel_Right                                              :: CA.kChannelLabel_Right
kChannelLabel_Center                                             :: CA.kChannelLabel_Center
kChannelLabel_LFEScreen                                          :: CA.kChannelLabel_LFEScreen
kChannelLabel_LeftSurround                                       :: CA.kChannelLabel_LeftSurround
kChannelLabel_RightSurround                                      :: CA.kChannelLabel_RightSurround
kChannelLabel_LeftCenter                                         :: CA.kChannelLabel_LeftCenter
kChannelLabel_RightCenter                                        :: CA.kChannelLabel_RightCenter
kChannelLabel_CenterSurround                                     :: CA.kChannelLabel_CenterSurround
kChannelLabel_LeftSurroundDirect                                 :: CA.kChannelLabel_LeftSurroundDirect
kChannelLabel_RightSurroundDirect                                :: CA.kChannelLabel_RightSurroundDirect
kChannelLabel_TopCenterSurround                                  :: CA.kChannelLabel_TopCenterSurround
kChannelLabel_VerticalHeightLeft                                 :: CA.kChannelLabel_VerticalHeightLeft
kChannelLabel_VerticalHeightCenter                               :: CA.kChannelLabel_VerticalHeightCenter
kChannelLabel_VerticalHeightRight                                :: CA.kChannelLabel_VerticalHeightRight
kChannelLabel_TopBackLeft                                        :: CA.kChannelLabel_TopBackLeft
kChannelLabel_TopBackCenter                                      :: CA.kChannelLabel_TopBackCenter
kChannelLabel_TopBackRight                                       :: CA.kChannelLabel_TopBackRight
kChannelLabel_RearSurroundLeft                                   :: CA.kChannelLabel_RearSurroundLeft
kChannelLabel_RearSurroundRight                                  :: CA.kChannelLabel_RearSurroundRight
kChannelLabel_LeftWide                                           :: CA.kChannelLabel_LeftWide
kChannelLabel_RightWide                                          :: CA.kChannelLabel_RightWide
kChannelLabel_LFE2                                               :: CA.kChannelLabel_LFE2
kChannelLabel_LeftTotal                                          :: CA.kChannelLabel_LeftTotal
kChannelLabel_RightTotal                                         :: CA.kChannelLabel_RightTotal
kChannelLabel_HearingImpaired                                    :: CA.kChannelLabel_HearingImpaired
kChannelLabel_Narration                                          :: CA.kChannelLabel_Narration
kChannelLabel_Mono                                               :: CA.kChannelLabel_Mono
kChannelLabel_DialogCentricMix                                   :: CA.kChannelLabel_DialogCentricMix
kChannelLabel_CenterSurroundDirect                               :: CA.kChannelLabel_CenterSurroundDirect
kChannelLabel_Haptic                                             :: CA.kChannelLabel_Haptic
kChannelLabel_LeftTopFront                                       :: CA.kChannelLabel_LeftTopFront
kChannelLabel_CenterTopFront                                     :: CA.kChannelLabel_CenterTopFront
kChannelLabel_RightTopFront                                      :: CA.kChannelLabel_RightTopFront
kChannelLabel_LeftTopMiddle                                      :: CA.kChannelLabel_LeftTopMiddle
kChannelLabel_CenterTopMiddle                                    :: CA.kChannelLabel_CenterTopMiddle
kChannelLabel_RightTopMiddle                                     :: CA.kChannelLabel_RightTopMiddle
kChannelLabel_LeftTopRear                                        :: CA.kChannelLabel_LeftTopRear
kChannelLabel_CenterTopRear                                      :: CA.kChannelLabel_CenterTopRear
kChannelLabel_RightTopRear                                       :: CA.kChannelLabel_RightTopRear
kChannelLabel_LeftSideSurround                                   :: CA.kChannelLabel_LeftSideSurround
kChannelLabel_RightSideSurround                                  :: CA.kChannelLabel_RightSideSurround
kChannelLabel_LeftBottom                                         :: CA.kChannelLabel_LeftBottom
kChannelLabel_RightBottom                                        :: CA.kChannelLabel_RightBottom
kChannelLabel_CenterBottom                                       :: CA.kChannelLabel_CenterBottom
kChannelLabel_LeftTopSurround                                    :: CA.kChannelLabel_LeftTopSurround
kChannelLabel_RightTopSurround                                   :: CA.kChannelLabel_RightTopSurround
kChannelLabel_LFE3                                               :: CA.kChannelLabel_LFE3
kChannelLabel_LeftBackSurround                                   :: CA.kChannelLabel_LeftBackSurround
kChannelLabel_RightBackSurround                                  :: CA.kChannelLabel_RightBackSurround
kChannelLabel_LeftEdgeOfScreen                                   :: CA.kChannelLabel_LeftEdgeOfScreen
kChannelLabel_RightEdgeOfScreen                                  :: CA.kChannelLabel_RightEdgeOfScreen
kChannelLabel_Ambisonic_W                                        :: CA.kChannelLabel_Ambisonic_W
kChannelLabel_Ambisonic_X                                        :: CA.kChannelLabel_Ambisonic_X
kChannelLabel_Ambisonic_Y                                        :: CA.kChannelLabel_Ambisonic_Y
kChannelLabel_Ambisonic_Z                                        :: CA.kChannelLabel_Ambisonic_Z
kChannelLabel_MS_Mid                                             :: CA.kChannelLabel_MS_Mid
kChannelLabel_MS_Side                                            :: CA.kChannelLabel_MS_Side
kChannelLabel_XY_X                                               :: CA.kChannelLabel_XY_X
kChannelLabel_XY_Y                                               :: CA.kChannelLabel_XY_Y
kChannelLabel_BinauralLeft                                       :: CA.kChannelLabel_BinauralLeft
kChannelLabel_BinauralRight                                      :: CA.kChannelLabel_BinauralRight
kChannelLabel_HeadphonesLeft                                     :: CA.kChannelLabel_HeadphonesLeft
kChannelLabel_HeadphonesRight                                    :: CA.kChannelLabel_HeadphonesRight
kChannelLabel_ClickTrack                                         :: CA.kChannelLabel_ClickTrack
kChannelLabel_ForeignLanguage                                    :: CA.kChannelLabel_ForeignLanguage
kChannelLabel_Discrete                                           :: CA.kChannelLabel_Discrete
kChannelLabel_Discrete_0                                         :: CA.kChannelLabel_Discrete_0
kChannelLabel_Discrete_1                                         :: CA.kChannelLabel_Discrete_1
kChannelLabel_Discrete_2                                         :: CA.kChannelLabel_Discrete_2
kChannelLabel_Discrete_3                                         :: CA.kChannelLabel_Discrete_3
kChannelLabel_Discrete_4                                         :: CA.kChannelLabel_Discrete_4
kChannelLabel_Discrete_5                                         :: CA.kChannelLabel_Discrete_5
kChannelLabel_Discrete_6                                         :: CA.kChannelLabel_Discrete_6
kChannelLabel_Discrete_7                                         :: CA.kChannelLabel_Discrete_7
kChannelLabel_Discrete_8                                         :: CA.kChannelLabel_Discrete_8
kChannelLabel_Discrete_9                                         :: CA.kChannelLabel_Discrete_9
kChannelLabel_Discrete_10                                        :: CA.kChannelLabel_Discrete_10
kChannelLabel_Discrete_11                                        :: CA.kChannelLabel_Discrete_11
kChannelLabel_Discrete_12                                        :: CA.kChannelLabel_Discrete_12
kChannelLabel_Discrete_13                                        :: CA.kChannelLabel_Discrete_13
kChannelLabel_Discrete_14                                        :: CA.kChannelLabel_Discrete_14
kChannelLabel_Discrete_15                                        :: CA.kChannelLabel_Discrete_15
kChannelLabel_Discrete_65535                                     :: CA.kChannelLabel_Discrete_65535
kChannelLabel_HOA_ACN                                            :: CA.kChannelLabel_HOA_ACN
kChannelLabel_HOA_ACN_0                                          :: CA.kChannelLabel_HOA_ACN_0
kChannelLabel_HOA_ACN_1                                          :: CA.kChannelLabel_HOA_ACN_1
kChannelLabel_HOA_ACN_2                                          :: CA.kChannelLabel_HOA_ACN_2
kChannelLabel_HOA_ACN_3                                          :: CA.kChannelLabel_HOA_ACN_3
kChannelLabel_HOA_ACN_4                                          :: CA.kChannelLabel_HOA_ACN_4
kChannelLabel_HOA_ACN_5                                          :: CA.kChannelLabel_HOA_ACN_5
kChannelLabel_HOA_ACN_6                                          :: CA.kChannelLabel_HOA_ACN_6
kChannelLabel_HOA_ACN_7                                          :: CA.kChannelLabel_HOA_ACN_7
kChannelLabel_HOA_ACN_8                                          :: CA.kChannelLabel_HOA_ACN_8
kChannelLabel_HOA_ACN_9                                          :: CA.kChannelLabel_HOA_ACN_9
kChannelLabel_HOA_ACN_10                                         :: CA.kChannelLabel_HOA_ACN_10
kChannelLabel_HOA_ACN_11                                         :: CA.kChannelLabel_HOA_ACN_11
kChannelLabel_HOA_ACN_12                                         :: CA.kChannelLabel_HOA_ACN_12
kChannelLabel_HOA_ACN_13                                         :: CA.kChannelLabel_HOA_ACN_13
kChannelLabel_HOA_ACN_14                                         :: CA.kChannelLabel_HOA_ACN_14
kChannelLabel_HOA_ACN_15                                         :: CA.kChannelLabel_HOA_ACN_15
kChannelLabel_HOA_ACN_65024                                      :: CA.kChannelLabel_HOA_ACN_65024
kChannelLabel_HOA_SN3D                                           :: CA.kChannelLabel_HOA_SN3D
kChannelLabel_HOA_N3D                                            :: CA.kChannelLabel_HOA_N3D
kChannelLabel_Object                                             :: CA.kChannelLabel_Object
kChannelLabel_BeginReserved                                      :: CA.kChannelLabel_BeginReserved
kChannelLabel_EndReserved                                        :: CA.kChannelLabel_EndReserved
kChannelLayoutTag_UseChannelDescriptions                         :: CA.kChannelLayoutTag_UseChannelDescriptions
kChannelLayoutTag_UseChannelBitmap                               :: CA.kChannelLayoutTag_UseChannelBitmap
kChannelLayoutTag_Mono                                           :: CA.kChannelLayoutTag_Mono
kChannelLayoutTag_Stereo                                         :: CA.kChannelLayoutTag_Stereo
kChannelLayoutTag_StereoHeadphones                               :: CA.kChannelLayoutTag_StereoHeadphones
kChannelLayoutTag_MatrixStereo                                   :: CA.kChannelLayoutTag_MatrixStereo
kChannelLayoutTag_MidSide                                        :: CA.kChannelLayoutTag_MidSide
kChannelLayoutTag_XY                                             :: CA.kChannelLayoutTag_XY
kChannelLayoutTag_Binaural                                       :: CA.kChannelLayoutTag_Binaural
kChannelLayoutTag_Ambisonic_B_Format                             :: CA.kChannelLayoutTag_Ambisonic_B_Format
kChannelLayoutTag_Quadraphonic                                   :: CA.kChannelLayoutTag_Quadraphonic
kChannelLayoutTag_Pentagonal                                     :: CA.kChannelLayoutTag_Pentagonal
kChannelLayoutTag_Hexagonal                                      :: CA.kChannelLayoutTag_Hexagonal
kChannelLayoutTag_Octagonal                                      :: CA.kChannelLayoutTag_Octagonal
kChannelLayoutTag_Cube                                           :: CA.kChannelLayoutTag_Cube
kChannelLayoutTag_MPEG_1_0                                       :: CA.kChannelLayoutTag_MPEG_1_0
kChannelLayoutTag_MPEG_2_0                                       :: CA.kChannelLayoutTag_MPEG_2_0
kChannelLayoutTag_MPEG_3_0_A                                     :: CA.kChannelLayoutTag_MPEG_3_0_A
kChannelLayoutTag_MPEG_3_0_B                                     :: CA.kChannelLayoutTag_MPEG_3_0_B
kChannelLayoutTag_MPEG_4_0_A                                     :: CA.kChannelLayoutTag_MPEG_4_0_A
kChannelLayoutTag_MPEG_4_0_B                                     :: CA.kChannelLayoutTag_MPEG_4_0_B
kChannelLayoutTag_MPEG_5_0_A                                     :: CA.kChannelLayoutTag_MPEG_5_0_A
kChannelLayoutTag_MPEG_5_0_B                                     :: CA.kChannelLayoutTag_MPEG_5_0_B
kChannelLayoutTag_MPEG_5_0_C                                     :: CA.kChannelLayoutTag_MPEG_5_0_C
kChannelLayoutTag_MPEG_5_0_D                                     :: CA.kChannelLayoutTag_MPEG_5_0_D
kChannelLayoutTag_MPEG_5_1_A                                     :: CA.kChannelLayoutTag_MPEG_5_1_A
kChannelLayoutTag_MPEG_5_1_B                                     :: CA.kChannelLayoutTag_MPEG_5_1_B
kChannelLayoutTag_MPEG_5_1_C                                     :: CA.kChannelLayoutTag_MPEG_5_1_C
kChannelLayoutTag_MPEG_5_1_D                                     :: CA.kChannelLayoutTag_MPEG_5_1_D
kChannelLayoutTag_MPEG_6_1_A                                     :: CA.kChannelLayoutTag_MPEG_6_1_A
kChannelLayoutTag_MPEG_7_1_A                                     :: CA.kChannelLayoutTag_MPEG_7_1_A
kChannelLayoutTag_MPEG_7_1_B                                     :: CA.kChannelLayoutTag_MPEG_7_1_B
kChannelLayoutTag_MPEG_7_1_C                                     :: CA.kChannelLayoutTag_MPEG_7_1_C
kChannelLayoutTag_Emagic_Default_7_1                             :: CA.kChannelLayoutTag_Emagic_Default_7_1
kChannelLayoutTag_SMPTE_DTV                                      :: CA.kChannelLayoutTag_SMPTE_DTV
kChannelLayoutTag_ITU_1_0                                        :: CA.kChannelLayoutTag_ITU_1_0
kChannelLayoutTag_ITU_2_0                                        :: CA.kChannelLayoutTag_ITU_2_0
kChannelLayoutTag_ITU_2_1                                        :: CA.kChannelLayoutTag_ITU_2_1
kChannelLayoutTag_ITU_2_2                                        :: CA.kChannelLayoutTag_ITU_2_2
kChannelLayoutTag_ITU_3_0                                        :: CA.kChannelLayoutTag_ITU_3_0
kChannelLayoutTag_ITU_3_1                                        :: CA.kChannelLayoutTag_ITU_3_1
kChannelLayoutTag_ITU_3_2                                        :: CA.kChannelLayoutTag_ITU_3_2
kChannelLayoutTag_ITU_3_2_1                                      :: CA.kChannelLayoutTag_ITU_3_2_1
kChannelLayoutTag_ITU_3_4_1                                      :: CA.kChannelLayoutTag_ITU_3_4_1
kChannelLayoutTag_DVD_0                                          :: CA.kChannelLayoutTag_DVD_0
kChannelLayoutTag_DVD_1                                          :: CA.kChannelLayoutTag_DVD_1
kChannelLayoutTag_DVD_2                                          :: CA.kChannelLayoutTag_DVD_2
kChannelLayoutTag_DVD_3                                          :: CA.kChannelLayoutTag_DVD_3
kChannelLayoutTag_DVD_4                                          :: CA.kChannelLayoutTag_DVD_4
kChannelLayoutTag_DVD_5                                          :: CA.kChannelLayoutTag_DVD_5
kChannelLayoutTag_DVD_6                                          :: CA.kChannelLayoutTag_DVD_6
kChannelLayoutTag_DVD_7                                          :: CA.kChannelLayoutTag_DVD_7
kChannelLayoutTag_DVD_8                                          :: CA.kChannelLayoutTag_DVD_8
kChannelLayoutTag_DVD_9                                          :: CA.kChannelLayoutTag_DVD_9
kChannelLayoutTag_DVD_10                                         :: CA.kChannelLayoutTag_DVD_10
kChannelLayoutTag_DVD_11                                         :: CA.kChannelLayoutTag_DVD_11
kChannelLayoutTag_DVD_12                                         :: CA.kChannelLayoutTag_DVD_12
kChannelLayoutTag_DVD_13                                         :: CA.kChannelLayoutTag_DVD_13
kChannelLayoutTag_DVD_14                                         :: CA.kChannelLayoutTag_DVD_14
kChannelLayoutTag_DVD_15                                         :: CA.kChannelLayoutTag_DVD_15
kChannelLayoutTag_DVD_16                                         :: CA.kChannelLayoutTag_DVD_16
kChannelLayoutTag_DVD_17                                         :: CA.kChannelLayoutTag_DVD_17
kChannelLayoutTag_DVD_18                                         :: CA.kChannelLayoutTag_DVD_18
kChannelLayoutTag_DVD_19                                         :: CA.kChannelLayoutTag_DVD_19
kChannelLayoutTag_DVD_20                                         :: CA.kChannelLayoutTag_DVD_20
kChannelLayoutTag_AudioUnit_4                                    :: CA.kChannelLayoutTag_AudioUnit_4
kChannelLayoutTag_AudioUnit_5                                    :: CA.kChannelLayoutTag_AudioUnit_5
kChannelLayoutTag_AudioUnit_6                                    :: CA.kChannelLayoutTag_AudioUnit_6
kChannelLayoutTag_AudioUnit_8                                    :: CA.kChannelLayoutTag_AudioUnit_8
kChannelLayoutTag_AudioUnit_5_0                                  :: CA.kChannelLayoutTag_AudioUnit_5_0
kChannelLayoutTag_AudioUnit_6_0                                  :: CA.kChannelLayoutTag_AudioUnit_6_0
kChannelLayoutTag_AudioUnit_7_0                                  :: CA.kChannelLayoutTag_AudioUnit_7_0
kChannelLayoutTag_AudioUnit_7_0_Front                            :: CA.kChannelLayoutTag_AudioUnit_7_0_Front
kChannelLayoutTag_AudioUnit_5_1                                  :: CA.kChannelLayoutTag_AudioUnit_5_1
kChannelLayoutTag_AudioUnit_6_1                                  :: CA.kChannelLayoutTag_AudioUnit_6_1
kChannelLayoutTag_AudioUnit_7_1                                  :: CA.kChannelLayoutTag_AudioUnit_7_1
kChannelLayoutTag_AudioUnit_7_1_Front                            :: CA.kChannelLayoutTag_AudioUnit_7_1_Front
kChannelLayoutTag_AAC_3_0                                        :: CA.kChannelLayoutTag_AAC_3_0
kChannelLayoutTag_AAC_Quadraphonic                               :: CA.kChannelLayoutTag_AAC_Quadraphonic
kChannelLayoutTag_AAC_4_0                                        :: CA.kChannelLayoutTag_AAC_4_0
kChannelLayoutTag_AAC_5_0                                        :: CA.kChannelLayoutTag_AAC_5_0
kChannelLayoutTag_AAC_5_1                                        :: CA.kChannelLayoutTag_AAC_5_1
kChannelLayoutTag_AAC_6_0                                        :: CA.kChannelLayoutTag_AAC_6_0
kChannelLayoutTag_AAC_6_1                                        :: CA.kChannelLayoutTag_AAC_6_1
kChannelLayoutTag_AAC_7_0                                        :: CA.kChannelLayoutTag_AAC_7_0
kChannelLayoutTag_AAC_7_1                                        :: CA.kChannelLayoutTag_AAC_7_1
kChannelLayoutTag_AAC_7_1_B                                      :: CA.kChannelLayoutTag_AAC_7_1_B
kChannelLayoutTag_AAC_7_1_C                                      :: CA.kChannelLayoutTag_AAC_7_1_C
kChannelLayoutTag_AAC_Octagonal                                  :: CA.kChannelLayoutTag_AAC_Octagonal
kChannelLayoutTag_TMH_10_2_std                                   :: CA.kChannelLayoutTag_TMH_10_2_std
kChannelLayoutTag_TMH_10_2_full                                  :: CA.kChannelLayoutTag_TMH_10_2_full
kChannelLayoutTag_AC3_1_0_1                                      :: CA.kChannelLayoutTag_AC3_1_0_1
kChannelLayoutTag_AC3_3_0                                        :: CA.kChannelLayoutTag_AC3_3_0
kChannelLayoutTag_AC3_3_1                                        :: CA.kChannelLayoutTag_AC3_3_1
kChannelLayoutTag_AC3_3_0_1                                      :: CA.kChannelLayoutTag_AC3_3_0_1
kChannelLayoutTag_AC3_2_1_1                                      :: CA.kChannelLayoutTag_AC3_2_1_1
kChannelLayoutTag_AC3_3_1_1                                      :: CA.kChannelLayoutTag_AC3_3_1_1
kChannelLayoutTag_EAC_6_0_A                                      :: CA.kChannelLayoutTag_EAC_6_0_A
kChannelLayoutTag_EAC_7_0_A                                      :: CA.kChannelLayoutTag_EAC_7_0_A
kChannelLayoutTag_EAC3_6_1_A                                     :: CA.kChannelLayoutTag_EAC3_6_1_A
kChannelLayoutTag_EAC3_6_1_B                                     :: CA.kChannelLayoutTag_EAC3_6_1_B
kChannelLayoutTag_EAC3_6_1_C                                     :: CA.kChannelLayoutTag_EAC3_6_1_C
kChannelLayoutTag_EAC3_7_1_A                                     :: CA.kChannelLayoutTag_EAC3_7_1_A
kChannelLayoutTag_EAC3_7_1_B                                     :: CA.kChannelLayoutTag_EAC3_7_1_B
kChannelLayoutTag_EAC3_7_1_C                                     :: CA.kChannelLayoutTag_EAC3_7_1_C
kChannelLayoutTag_EAC3_7_1_D                                     :: CA.kChannelLayoutTag_EAC3_7_1_D
kChannelLayoutTag_EAC3_7_1_E                                     :: CA.kChannelLayoutTag_EAC3_7_1_E
kChannelLayoutTag_EAC3_7_1_F                                     :: CA.kChannelLayoutTag_EAC3_7_1_F
kChannelLayoutTag_EAC3_7_1_G                                     :: CA.kChannelLayoutTag_EAC3_7_1_G
kChannelLayoutTag_EAC3_7_1_H                                     :: CA.kChannelLayoutTag_EAC3_7_1_H
kChannelLayoutTag_DTS_3_1                                        :: CA.kChannelLayoutTag_DTS_3_1
kChannelLayoutTag_DTS_4_1                                        :: CA.kChannelLayoutTag_DTS_4_1
kChannelLayoutTag_DTS_6_0_A                                      :: CA.kChannelLayoutTag_DTS_6_0_A
kChannelLayoutTag_DTS_6_0_B                                      :: CA.kChannelLayoutTag_DTS_6_0_B
kChannelLayoutTag_DTS_6_0_C                                      :: CA.kChannelLayoutTag_DTS_6_0_C
kChannelLayoutTag_DTS_6_1_A                                      :: CA.kChannelLayoutTag_DTS_6_1_A
kChannelLayoutTag_DTS_6_1_B                                      :: CA.kChannelLayoutTag_DTS_6_1_B
kChannelLayoutTag_DTS_6_1_C                                      :: CA.kChannelLayoutTag_DTS_6_1_C
kChannelLayoutTag_DTS_7_0                                        :: CA.kChannelLayoutTag_DTS_7_0
kChannelLayoutTag_DTS_7_1                                        :: CA.kChannelLayoutTag_DTS_7_1
kChannelLayoutTag_DTS_8_0_A                                      :: CA.kChannelLayoutTag_DTS_8_0_A
kChannelLayoutTag_DTS_8_0_B                                      :: CA.kChannelLayoutTag_DTS_8_0_B
kChannelLayoutTag_DTS_8_1_A                                      :: CA.kChannelLayoutTag_DTS_8_1_A
kChannelLayoutTag_DTS_8_1_B                                      :: CA.kChannelLayoutTag_DTS_8_1_B
kChannelLayoutTag_DTS_6_1_D                                      :: CA.kChannelLayoutTag_DTS_6_1_D
kChannelLayoutTag_WAVE_2_1                                       :: CA.kChannelLayoutTag_WAVE_2_1
kChannelLayoutTag_WAVE_3_0                                       :: CA.kChannelLayoutTag_WAVE_3_0
kChannelLayoutTag_WAVE_4_0_A                                     :: CA.kChannelLayoutTag_WAVE_4_0_A
kChannelLayoutTag_WAVE_4_0_B                                     :: CA.kChannelLayoutTag_WAVE_4_0_B
kChannelLayoutTag_WAVE_5_0_A                                     :: CA.kChannelLayoutTag_WAVE_5_0_A
kChannelLayoutTag_WAVE_5_0_B                                     :: CA.kChannelLayoutTag_WAVE_5_0_B
kChannelLayoutTag_WAVE_5_1_A                                     :: CA.kChannelLayoutTag_WAVE_5_1_A
kChannelLayoutTag_WAVE_5_1_B                                     :: CA.kChannelLayoutTag_WAVE_5_1_B
kChannelLayoutTag_WAVE_6_1                                       :: CA.kChannelLayoutTag_WAVE_6_1
kChannelLayoutTag_WAVE_7_1                                       :: CA.kChannelLayoutTag_WAVE_7_1
kChannelLayoutTag_HOA_ACN_SN3D                                   :: CA.kChannelLayoutTag_HOA_ACN_SN3D
kChannelLayoutTag_HOA_ACN_N3D                                    :: CA.kChannelLayoutTag_HOA_ACN_N3D
kChannelLayoutTag_Atmos_5_1_2                                    :: CA.kChannelLayoutTag_Atmos_5_1_2
kChannelLayoutTag_Atmos_5_1_4                                    :: CA.kChannelLayoutTag_Atmos_5_1_4
kChannelLayoutTag_Atmos_7_1_2                                    :: CA.kChannelLayoutTag_Atmos_7_1_2
kChannelLayoutTag_Atmos_7_1_4                                    :: CA.kChannelLayoutTag_Atmos_7_1_4
kChannelLayoutTag_Atmos_9_1_6                                    :: CA.kChannelLayoutTag_Atmos_9_1_6
kChannelLayoutTag_Logic_Mono                                     :: CA.kChannelLayoutTag_Logic_Mono
kChannelLayoutTag_Logic_Stereo                                   :: CA.kChannelLayoutTag_Logic_Stereo
kChannelLayoutTag_Logic_Quadraphonic                             :: CA.kChannelLayoutTag_Logic_Quadraphonic
kChannelLayoutTag_Logic_4_0_A                                    :: CA.kChannelLayoutTag_Logic_4_0_A
kChannelLayoutTag_Logic_4_0_B                                    :: CA.kChannelLayoutTag_Logic_4_0_B
kChannelLayoutTag_Logic_4_0_C                                    :: CA.kChannelLayoutTag_Logic_4_0_C
kChannelLayoutTag_Logic_5_0_A                                    :: CA.kChannelLayoutTag_Logic_5_0_A
kChannelLayoutTag_Logic_5_0_B                                    :: CA.kChannelLayoutTag_Logic_5_0_B
kChannelLayoutTag_Logic_5_0_C                                    :: CA.kChannelLayoutTag_Logic_5_0_C
kChannelLayoutTag_Logic_5_0_D                                    :: CA.kChannelLayoutTag_Logic_5_0_D
kChannelLayoutTag_Logic_5_1_A                                    :: CA.kChannelLayoutTag_Logic_5_1_A
kChannelLayoutTag_Logic_5_1_B                                    :: CA.kChannelLayoutTag_Logic_5_1_B
kChannelLayoutTag_Logic_5_1_C                                    :: CA.kChannelLayoutTag_Logic_5_1_C
kChannelLayoutTag_Logic_5_1_D                                    :: CA.kChannelLayoutTag_Logic_5_1_D
kChannelLayoutTag_Logic_6_0_A                                    :: CA.kChannelLayoutTag_Logic_6_0_A
kChannelLayoutTag_Logic_6_0_B                                    :: CA.kChannelLayoutTag_Logic_6_0_B
kChannelLayoutTag_Logic_6_0_C                                    :: CA.kChannelLayoutTag_Logic_6_0_C
kChannelLayoutTag_Logic_6_1_A                                    :: CA.kChannelLayoutTag_Logic_6_1_A
kChannelLayoutTag_Logic_6_1_B                                    :: CA.kChannelLayoutTag_Logic_6_1_B
kChannelLayoutTag_Logic_6_1_C                                    :: CA.kChannelLayoutTag_Logic_6_1_C
kChannelLayoutTag_Logic_6_1_D                                    :: CA.kChannelLayoutTag_Logic_6_1_D
kChannelLayoutTag_Logic_7_1_A                                    :: CA.kChannelLayoutTag_Logic_7_1_A
kChannelLayoutTag_Logic_7_1_B                                    :: CA.kChannelLayoutTag_Logic_7_1_B
kChannelLayoutTag_Logic_7_1_C                                    :: CA.kChannelLayoutTag_Logic_7_1_C
kChannelLayoutTag_Logic_7_1_SDDS_A                               :: CA.kChannelLayoutTag_Logic_7_1_SDDS_A
kChannelLayoutTag_Logic_7_1_SDDS_B                               :: CA.kChannelLayoutTag_Logic_7_1_SDDS_B
kChannelLayoutTag_Logic_7_1_SDDS_C                               :: CA.kChannelLayoutTag_Logic_7_1_SDDS_C
kChannelLayoutTag_Logic_Atmos_5_1_2                              :: CA.kChannelLayoutTag_Logic_Atmos_5_1_2
kChannelLayoutTag_Logic_Atmos_5_1_4                              :: CA.kChannelLayoutTag_Logic_Atmos_5_1_4
kChannelLayoutTag_Logic_Atmos_7_1_2                              :: CA.kChannelLayoutTag_Logic_Atmos_7_1_2
kChannelLayoutTag_Logic_Atmos_7_1_4_A                            :: CA.kChannelLayoutTag_Logic_Atmos_7_1_4_A
kChannelLayoutTag_Logic_Atmos_7_1_4_B                            :: CA.kChannelLayoutTag_Logic_Atmos_7_1_4_B
kChannelLayoutTag_Logic_Atmos_7_1_6                              :: CA.kChannelLayoutTag_Logic_Atmos_7_1_6
kChannelLayoutTag_DiscreteInOrder                                :: CA.kChannelLayoutTag_DiscreteInOrder
kChannelLayoutTag_CICP_1                                         :: CA.kChannelLayoutTag_CICP_1
kChannelLayoutTag_CICP_2                                         :: CA.kChannelLayoutTag_CICP_2
kChannelLayoutTag_CICP_3                                         :: CA.kChannelLayoutTag_CICP_3
kChannelLayoutTag_CICP_4                                         :: CA.kChannelLayoutTag_CICP_4
kChannelLayoutTag_CICP_5                                         :: CA.kChannelLayoutTag_CICP_5
kChannelLayoutTag_CICP_6                                         :: CA.kChannelLayoutTag_CICP_6
kChannelLayoutTag_CICP_7                                         :: CA.kChannelLayoutTag_CICP_7
kChannelLayoutTag_CICP_9                                         :: CA.kChannelLayoutTag_CICP_9
kChannelLayoutTag_CICP_10                                        :: CA.kChannelLayoutTag_CICP_10
kChannelLayoutTag_CICP_11                                        :: CA.kChannelLayoutTag_CICP_11
kChannelLayoutTag_CICP_12                                        :: CA.kChannelLayoutTag_CICP_12
kChannelLayoutTag_CICP_13                                        :: CA.kChannelLayoutTag_CICP_13
kChannelLayoutTag_CICP_14                                        :: CA.kChannelLayoutTag_CICP_14
kChannelLayoutTag_CICP_15                                        :: CA.kChannelLayoutTag_CICP_15
kChannelLayoutTag_CICP_16                                        :: CA.kChannelLayoutTag_CICP_16
kChannelLayoutTag_CICP_17                                        :: CA.kChannelLayoutTag_CICP_17
kChannelLayoutTag_CICP_18                                        :: CA.kChannelLayoutTag_CICP_18
kChannelLayoutTag_CICP_19                                        :: CA.kChannelLayoutTag_CICP_19
kChannelLayoutTag_CICP_20                                        :: CA.kChannelLayoutTag_CICP_20
kChannelLayoutTag_Ogg_3_0                                        :: CA.kChannelLayoutTag_Ogg_3_0
kChannelLayoutTag_Ogg_4_0                                        :: CA.kChannelLayoutTag_Ogg_4_0
kChannelLayoutTag_Ogg_5_0                                        :: CA.kChannelLayoutTag_Ogg_5_0
kChannelLayoutTag_Ogg_5_1                                        :: CA.kChannelLayoutTag_Ogg_5_1
kChannelLayoutTag_Ogg_6_1                                        :: CA.kChannelLayoutTag_Ogg_6_1
kChannelLayoutTag_Ogg_7_1                                        :: CA.kChannelLayoutTag_Ogg_7_1
kChannelLayoutTag_MPEG_5_0_E                                     :: CA.kChannelLayoutTag_MPEG_5_0_E
kChannelLayoutTag_MPEG_5_1_E                                     :: CA.kChannelLayoutTag_MPEG_5_1_E
kChannelLayoutTag_MPEG_6_1_B                                     :: CA.kChannelLayoutTag_MPEG_6_1_B
kChannelLayoutTag_MPEG_7_1_D                                     :: CA.kChannelLayoutTag_MPEG_7_1_D
kChannelLayoutTag_BeginReserved                                  :: CA.kChannelLayoutTag_BeginReserved
kChannelLayoutTag_EndReserved                                    :: CA.kChannelLayoutTag_EndReserved
kChannelLayoutTag_Unknown                                        :: CA.kChannelLayoutTag_Unknown
kHardwareNoError                                                 :: CA.kHardwareNoError
kHardwareNotRunningError                                         :: CA.kHardwareNotRunningError
kHardwareUnspecifiedError                                        :: CA.kHardwareUnspecifiedError
kHardwareUnknownPropertyError                                    :: CA.kHardwareUnknownPropertyError
kHardwareBadPropertySizeError                                    :: CA.kHardwareBadPropertySizeError
kHardwareIllegalOperationError                                   :: CA.kHardwareIllegalOperationError
kHardwareBadObjectError                                          :: CA.kHardwareBadObjectError
kHardwareBadDeviceError                                          :: CA.kHardwareBadDeviceError
kHardwareBadStreamError                                          :: CA.kHardwareBadStreamError
kHardwareUnsupportedOperationError                               :: CA.kHardwareUnsupportedOperationError
kHardwareNotReadyError                                           :: CA.kHardwareNotReadyError
kDeviceUnsupportedFormatError                                    :: CA.kDeviceUnsupportedFormatError
kDevicePermissionsError                                          :: CA.kDevicePermissionsError
kObjectUnknown                                                   :: CA.kObjectUnknown
kObjectPropertyScopeGlobal                                       :: CA.kObjectPropertyScopeGlobal
kObjectPropertyScopeInput                                        :: CA.kObjectPropertyScopeInput
kObjectPropertyScopeOutput                                       :: CA.kObjectPropertyScopeOutput
kObjectPropertyScopePlayThrough                                  :: CA.kObjectPropertyScopePlayThrough
kObjectPropertyElementMain                                       :: CA.kObjectPropertyElementMain
kObjectPropertyElementMaster                                     :: CA.kObjectPropertyElementMaster
kObjectPropertySelectorWildcard                                  :: CA.kObjectPropertySelectorWildcard
kObjectPropertyScopeWildcard                                     :: CA.kObjectPropertyScopeWildcard
kObjectPropertyElementWildcard                                   :: CA.kObjectPropertyElementWildcard
kObjectClassIDWildcard                                           :: CA.kObjectClassIDWildcard
kObjectClassID                                                   :: CA.kObjectClassID
kObjectPropertyBaseClass                                         :: CA.kObjectPropertyBaseClass
kObjectPropertyClass                                             :: CA.kObjectPropertyClass
kObjectPropertyOwner                                             :: CA.kObjectPropertyOwner
kObjectPropertyName                                              :: CA.kObjectPropertyName
kObjectPropertyModelName                                         :: CA.kObjectPropertyModelName
kObjectPropertyManufacturer                                      :: CA.kObjectPropertyManufacturer
kObjectPropertyElementName                                       :: CA.kObjectPropertyElementName
kObjectPropertyElementCategoryName                               :: CA.kObjectPropertyElementCategoryName
kObjectPropertyElementNumberName                                 :: CA.kObjectPropertyElementNumberName
kObjectPropertyOwnedObjects                                      :: CA.kObjectPropertyOwnedObjects
kObjectPropertyIdentify                                          :: CA.kObjectPropertyIdentify
kObjectPropertySerialNumber                                      :: CA.kObjectPropertySerialNumber
kObjectPropertyFirmwareVersion                                   :: CA.kObjectPropertyFirmwareVersion
kPlugInClassID                                                   :: CA.kPlugInClassID
kPlugInPropertyBundleID                                          :: CA.kPlugInPropertyBundleID
kPlugInPropertyDeviceList                                        :: CA.kPlugInPropertyDeviceList
kPlugInPropertyTranslateUIDToDevice                              :: CA.kPlugInPropertyTranslateUIDToDevice
kPlugInPropertyBoxList                                           :: CA.kPlugInPropertyBoxList
kPlugInPropertyTranslateUIDToBox                                 :: CA.kPlugInPropertyTranslateUIDToBox
kPlugInPropertyClockDeviceList                                   :: CA.kPlugInPropertyClockDeviceList
kPlugInPropertyTranslateUIDToClockDevice                         :: CA.kPlugInPropertyTranslateUIDToClockDevice
kTransportManagerClassID                                         :: CA.kTransportManagerClassID
kTransportManagerPropertyEndPointList                            :: CA.kTransportManagerPropertyEndPointList
kTransportManagerPropertyTranslateUIDToEndPoint                  :: CA.kTransportManagerPropertyTranslateUIDToEndPoint
kTransportManagerPropertyTransportType                           :: CA.kTransportManagerPropertyTransportType
kBoxClassID                                                      :: CA.kBoxClassID
kBoxPropertyBoxUID                                               :: CA.kBoxPropertyBoxUID
kBoxPropertyTransportType                                        :: CA.kBoxPropertyTransportType
kBoxPropertyHasAudio                                             :: CA.kBoxPropertyHasAudio
kBoxPropertyHasVideo                                             :: CA.kBoxPropertyHasVideo
kBoxPropertyHasMIDI                                              :: CA.kBoxPropertyHasMIDI
kBoxPropertyIsProtected                                          :: CA.kBoxPropertyIsProtected
kBoxPropertyAcquired                                             :: CA.kBoxPropertyAcquired
kBoxPropertyAcquisitionFailed                                    :: CA.kBoxPropertyAcquisitionFailed
kBoxPropertyDeviceList                                           :: CA.kBoxPropertyDeviceList
kBoxPropertyClockDeviceList                                      :: CA.kBoxPropertyClockDeviceList
kDeviceClassID                                                   :: CA.kDeviceClassID
kDeviceTransportTypeUnknown                                      :: CA.kDeviceTransportTypeUnknown
kDeviceTransportTypeBuiltIn                                      :: CA.kDeviceTransportTypeBuiltIn
kDeviceTransportTypeAggregate                                    :: CA.kDeviceTransportTypeAggregate
kDeviceTransportTypeVirtual                                      :: CA.kDeviceTransportTypeVirtual
kDeviceTransportTypePCI                                          :: CA.kDeviceTransportTypePCI
kDeviceTransportTypeUSB                                          :: CA.kDeviceTransportTypeUSB
kDeviceTransportTypeFireWire                                     :: CA.kDeviceTransportTypeFireWire
kDeviceTransportTypeBluetooth                                    :: CA.kDeviceTransportTypeBluetooth
kDeviceTransportTypeBluetoothLE                                  :: CA.kDeviceTransportTypeBluetoothLE
kDeviceTransportTypeHDMI                                         :: CA.kDeviceTransportTypeHDMI
kDeviceTransportTypeDisplayPort                                  :: CA.kDeviceTransportTypeDisplayPort
kDeviceTransportTypeAirPlay                                      :: CA.kDeviceTransportTypeAirPlay
kDeviceTransportTypeAVB                                          :: CA.kDeviceTransportTypeAVB
kDeviceTransportTypeThunderbolt                                  :: CA.kDeviceTransportTypeThunderbolt
kDeviceTransportTypeContinuityCaptureWired                       :: CA.kDeviceTransportTypeContinuityCaptureWired
kDeviceTransportTypeContinuityCaptureWireless                    :: CA.kDeviceTransportTypeContinuityCaptureWireless
kDeviceTransportTypeContinuityCapture                            :: CA.kDeviceTransportTypeContinuityCapture
kDevicePropertyConfigurationApplication                          :: CA.kDevicePropertyConfigurationApplication
kDevicePropertyDeviceUID                                         :: CA.kDevicePropertyDeviceUID
kDevicePropertyModelUID                                          :: CA.kDevicePropertyModelUID
kDevicePropertyTransportType                                     :: CA.kDevicePropertyTransportType
kDevicePropertyRelatedDevices                                    :: CA.kDevicePropertyRelatedDevices
kDevicePropertyClockDomain                                       :: CA.kDevicePropertyClockDomain
kDevicePropertyDeviceIsAlive                                     :: CA.kDevicePropertyDeviceIsAlive
kDevicePropertyDeviceIsRunning                                   :: CA.kDevicePropertyDeviceIsRunning
kDevicePropertyDeviceCanBeDefaultDevice                          :: CA.kDevicePropertyDeviceCanBeDefaultDevice
kDevicePropertyDeviceCanBeDefaultSystemDevice                    :: CA.kDevicePropertyDeviceCanBeDefaultSystemDevice
kDevicePropertyLatency                                           :: CA.kDevicePropertyLatency
kDevicePropertyStreams                                           :: CA.kDevicePropertyStreams
kObjectPropertyControlList                                       :: CA.kObjectPropertyControlList
kDevicePropertySafetyOffset                                      :: CA.kDevicePropertySafetyOffset
kDevicePropertyNominalSampleRate                                 :: CA.kDevicePropertyNominalSampleRate
kDevicePropertyAvailableNominalSampleRates                       :: CA.kDevicePropertyAvailableNominalSampleRates
kDevicePropertyIcon                                              :: CA.kDevicePropertyIcon
kDevicePropertyIsHidden                                          :: CA.kDevicePropertyIsHidden
kDevicePropertyPreferredChannelsForStereo                        :: CA.kDevicePropertyPreferredChannelsForStereo
kDevicePropertyPreferredChannelLayout                            :: CA.kDevicePropertyPreferredChannelLayout
kClockDeviceClassID                                              :: CA.kClockDeviceClassID
kClockDevicePropertyDeviceUID                                    :: CA.kClockDevicePropertyDeviceUID
kClockDevicePropertyTransportType                                :: CA.kClockDevicePropertyTransportType
kClockDevicePropertyClockDomain                                  :: CA.kClockDevicePropertyClockDomain
kClockDevicePropertyDeviceIsAlive                                :: CA.kClockDevicePropertyDeviceIsAlive
kClockDevicePropertyDeviceIsRunning                              :: CA.kClockDevicePropertyDeviceIsRunning
kClockDevicePropertyLatency                                      :: CA.kClockDevicePropertyLatency
kClockDevicePropertyControlList                                  :: CA.kClockDevicePropertyControlList
kClockDevicePropertyNominalSampleRate                            :: CA.kClockDevicePropertyNominalSampleRate
kClockDevicePropertyAvailableNominalSampleRates                  :: CA.kClockDevicePropertyAvailableNominalSampleRates
kEndPointDeviceClassID                                           :: CA.kEndPointDeviceClassID
kEndPointDevicePropertyComposition                               :: CA.kEndPointDevicePropertyComposition
kEndPointDevicePropertyEndPointList                              :: CA.kEndPointDevicePropertyEndPointList
kEndPointDevicePropertyIsPrivate                                 :: CA.kEndPointDevicePropertyIsPrivate
kEndPointClassID                                                 :: CA.kEndPointClassID
kStreamClassID                                                   :: CA.kStreamClassID
kStreamTerminalTypeUnknown                                       :: CA.kStreamTerminalTypeUnknown
kStreamTerminalTypeLine                                          :: CA.kStreamTerminalTypeLine
kStreamTerminalTypeDigitalAudioInterface                         :: CA.kStreamTerminalTypeDigitalAudioInterface
kStreamTerminalTypeSpeaker                                       :: CA.kStreamTerminalTypeSpeaker
kStreamTerminalTypeHeadphones                                    :: CA.kStreamTerminalTypeHeadphones
kStreamTerminalTypeLFESpeaker                                    :: CA.kStreamTerminalTypeLFESpeaker
kStreamTerminalTypeReceiverSpeaker                               :: CA.kStreamTerminalTypeReceiverSpeaker
kStreamTerminalTypeMicrophone                                    :: CA.kStreamTerminalTypeMicrophone
kStreamTerminalTypeHeadsetMicrophone                             :: CA.kStreamTerminalTypeHeadsetMicrophone
kStreamTerminalTypeReceiverMicrophone                            :: CA.kStreamTerminalTypeReceiverMicrophone
kStreamTerminalTypeTTY                                           :: CA.kStreamTerminalTypeTTY
kStreamTerminalTypeHDMI                                          :: CA.kStreamTerminalTypeHDMI
kStreamTerminalTypeDisplayPort                                   :: CA.kStreamTerminalTypeDisplayPort
kStreamPropertyIsActive                                          :: CA.kStreamPropertyIsActive
kStreamPropertyDirection                                         :: CA.kStreamPropertyDirection
kStreamPropertyTerminalType                                      :: CA.kStreamPropertyTerminalType
kStreamPropertyStartingChannel                                   :: CA.kStreamPropertyStartingChannel
kStreamPropertyLatency                                           :: CA.kStreamPropertyLatency
kStreamPropertyVirtualFormat                                     :: CA.kStreamPropertyVirtualFormat
kStreamPropertyAvailableVirtualFormats                           :: CA.kStreamPropertyAvailableVirtualFormats
kStreamPropertyPhysicalFormat                                    :: CA.kStreamPropertyPhysicalFormat
kStreamPropertyAvailablePhysicalFormats                          :: CA.kStreamPropertyAvailablePhysicalFormats
kControlClassID                                                  :: CA.kControlClassID
kControlPropertyScope                                            :: CA.kControlPropertyScope
kControlPropertyElement                                          :: CA.kControlPropertyElement
kSliderControlClassID                                            :: CA.kSliderControlClassID
kSliderControlPropertyValue                                      :: CA.kSliderControlPropertyValue
kSliderControlPropertyRange                                      :: CA.kSliderControlPropertyRange
kLevelControlClassID                                             :: CA.kLevelControlClassID
kVolumeControlClassID                                            :: CA.kVolumeControlClassID
kLFEVolumeControlClassID                                         :: CA.kLFEVolumeControlClassID
kLevelControlPropertyScalarValue                                 :: CA.kLevelControlPropertyScalarValue
kLevelControlPropertyDecibelValue                                :: CA.kLevelControlPropertyDecibelValue
kLevelControlPropertyDecibelRange                                :: CA.kLevelControlPropertyDecibelRange
kLevelControlPropertyConvertScalarToDecibels                     :: CA.kLevelControlPropertyConvertScalarToDecibels
kLevelControlPropertyConvertDecibelsToScalar                     :: CA.kLevelControlPropertyConvertDecibelsToScalar
kBooleanControlClassID                                           :: CA.kBooleanControlClassID
kMuteControlClassID                                              :: CA.kMuteControlClassID
kSoloControlClassID                                              :: CA.kSoloControlClassID
kJackControlClassID                                              :: CA.kJackControlClassID
kLFEMuteControlClassID                                           :: CA.kLFEMuteControlClassID
kPhantomPowerControlClassID                                      :: CA.kPhantomPowerControlClassID
kPhaseInvertControlClassID                                       :: CA.kPhaseInvertControlClassID
kClipLightControlClassID                                         :: CA.kClipLightControlClassID
kTalkbackControlClassID                                          :: CA.kTalkbackControlClassID
kListenbackControlClassID                                        :: CA.kListenbackControlClassID
kBooleanControlPropertyValue                                     :: CA.kBooleanControlPropertyValue
kSelectorControlClassID                                          :: CA.kSelectorControlClassID
kDataSourceControlClassID                                        :: CA.kDataSourceControlClassID
kDataDestinationControlClassID                                   :: CA.kDataDestinationControlClassID
kClockSourceControlClassID                                       :: CA.kClockSourceControlClassID
kLineLevelControlClassID                                         :: CA.kLineLevelControlClassID
kHighPassFilterControlClassID                                    :: CA.kHighPassFilterControlClassID
kSelectorControlPropertyCurrentItem                              :: CA.kSelectorControlPropertyCurrentItem
kSelectorControlPropertyAvailableItems                           :: CA.kSelectorControlPropertyAvailableItems
kSelectorControlPropertyItemName                                 :: CA.kSelectorControlPropertyItemName
kSelectorControlPropertyItemKind                                 :: CA.kSelectorControlPropertyItemKind
kSelectorControlItemKindSpacer                                   :: CA.kSelectorControlItemKindSpacer
kClockSourceItemKindInternal                                     :: CA.kClockSourceItemKindInternal
kStereoPanControlClassID                                         :: CA.kStereoPanControlClassID
kStereoPanControlPropertyValue                                   :: CA.kStereoPanControlPropertyValue
kStereoPanControlPropertyPanningChannels                         :: CA.kStereoPanControlPropertyPanningChannels
kObjectSystemObject                                              :: CA.kObjectSystemObject
kObjectPropertyCreator                                           :: CA.kObjectPropertyCreator
kObjectPropertyListenerAdded                                     :: CA.kObjectPropertyListenerAdded
kObjectPropertyListenerRemoved                                   :: CA.kObjectPropertyListenerRemoved
kSystemObjectClassID                                             :: CA.kSystemObjectClassID
kHardwarePropertyDevices                                         :: CA.kHardwarePropertyDevices
kHardwarePropertyDefaultInputDevice                              :: CA.kHardwarePropertyDefaultInputDevice
kHardwarePropertyDefaultOutputDevice                             :: CA.kHardwarePropertyDefaultOutputDevice
kHardwarePropertyDefaultSystemOutputDevice                       :: CA.kHardwarePropertyDefaultSystemOutputDevice
kHardwarePropertyTranslateUIDToDevice                            :: CA.kHardwarePropertyTranslateUIDToDevice
kHardwarePropertyMixStereoToMono                                 :: CA.kHardwarePropertyMixStereoToMono
kHardwarePropertyPlugInList                                      :: CA.kHardwarePropertyPlugInList
kHardwarePropertyTranslateBundleIDToPlugIn                       :: CA.kHardwarePropertyTranslateBundleIDToPlugIn
kHardwarePropertyTransportManagerList                            :: CA.kHardwarePropertyTransportManagerList
kHardwarePropertyTranslateBundleIDToTransportManager             :: CA.kHardwarePropertyTranslateBundleIDToTransportManager
kHardwarePropertyBoxList                                         :: CA.kHardwarePropertyBoxList
kHardwarePropertyTranslateUIDToBox                               :: CA.kHardwarePropertyTranslateUIDToBox
kHardwarePropertyClockDeviceList                                 :: CA.kHardwarePropertyClockDeviceList
kHardwarePropertyTranslateUIDToClockDevice                       :: CA.kHardwarePropertyTranslateUIDToClockDevice
kHardwarePropertyProcessIsMain                                   :: CA.kHardwarePropertyProcessIsMain
kHardwarePropertyIsInitingOrExiting                              :: CA.kHardwarePropertyIsInitingOrExiting
kHardwarePropertyUserIDChanged                                   :: CA.kHardwarePropertyUserIDChanged
kHardwarePropertyProcessInputMute                                :: CA.kHardwarePropertyProcessInputMute
kHardwarePropertyProcessIsAudible                                :: CA.kHardwarePropertyProcessIsAudible
kHardwarePropertySleepingIsAllowed                               :: CA.kHardwarePropertySleepingIsAllowed
kHardwarePropertyUnloadingIsAllowed                              :: CA.kHardwarePropertyUnloadingIsAllowed
kHardwarePropertyHogModeIsAllowed                                :: CA.kHardwarePropertyHogModeIsAllowed
kHardwarePropertyUserSessionIsActiveOrHeadless                   :: CA.kHardwarePropertyUserSessionIsActiveOrHeadless
kHardwarePropertyServiceRestarted                                :: CA.kHardwarePropertyServiceRestarted
kHardwarePropertyPowerHint                                       :: CA.kHardwarePropertyPowerHint
kHardwarePropertyProcessObjectList                               :: CA.kHardwarePropertyProcessObjectList
kHardwarePropertyTranslatePIDToProcessObject                     :: CA.kHardwarePropertyTranslatePIDToProcessObject
kHardwarePropertyTapList                                         :: CA.kHardwarePropertyTapList
kHardwarePropertyTranslateUIDToTap                               :: CA.kHardwarePropertyTranslateUIDToTap
kPlugInCreateAggregateDevice                                     :: CA.kPlugInCreateAggregateDevice
kPlugInDestroyAggregateDevice                                    :: CA.kPlugInDestroyAggregateDevice
kTransportManagerCreateEndPointDevice                            :: CA.kTransportManagerCreateEndPointDevice
kTransportManagerDestroyEndPointDevice                           :: CA.kTransportManagerDestroyEndPointDevice
kDeviceStartTimeIsInputFlag                                      :: CA.kDeviceStartTimeIsInputFlag
kDeviceStartTimeDontConsultDeviceFlag                            :: CA.kDeviceStartTimeDontConsultDeviceFlag
kDeviceStartTimeDontConsultHALFlag                               :: CA.kDeviceStartTimeDontConsultHALFlag
kDevicePropertyPlugIn                                            :: CA.kDevicePropertyPlugIn
kDevicePropertyDeviceHasChanged                                  :: CA.kDevicePropertyDeviceHasChanged
kDevicePropertyDeviceIsRunningSomewhere                          :: CA.kDevicePropertyDeviceIsRunningSomewhere
kDeviceProcessorOverload                                         :: CA.kDeviceProcessorOverload
kDevicePropertyIOStoppedAbnormally                               :: CA.kDevicePropertyIOStoppedAbnormally
kDevicePropertyHogMode                                           :: CA.kDevicePropertyHogMode
kDevicePropertyBufferFrameSize                                   :: CA.kDevicePropertyBufferFrameSize
kDevicePropertyBufferFrameSizeRange                              :: CA.kDevicePropertyBufferFrameSizeRange
kDevicePropertyUsesVariableBufferFrameSizes                      :: CA.kDevicePropertyUsesVariableBufferFrameSizes
kDevicePropertyIOCycleUsage                                      :: CA.kDevicePropertyIOCycleUsage
kDevicePropertyStreamConfiguration                               :: CA.kDevicePropertyStreamConfiguration
kDevicePropertyIOProcStreamUsage                                 :: CA.kDevicePropertyIOProcStreamUsage
kDevicePropertyActualSampleRate                                  :: CA.kDevicePropertyActualSampleRate
kDevicePropertyClockDevice                                       :: CA.kDevicePropertyClockDevice
kDevicePropertyIOThreadOSWorkgroup                               :: CA.kDevicePropertyIOThreadOSWorkgroup
kDevicePropertyProcessMute                                       :: CA.kDevicePropertyProcessMute
kDevicePropertyJackIsConnected                                   :: CA.kDevicePropertyJackIsConnected
kDevicePropertyVolumeScalar                                      :: CA.kDevicePropertyVolumeScalar
kDevicePropertyVolumeDecibels                                    :: CA.kDevicePropertyVolumeDecibels
kDevicePropertyVolumeRangeDecibels                               :: CA.kDevicePropertyVolumeRangeDecibels
kDevicePropertyVolumeScalarToDecibels                            :: CA.kDevicePropertyVolumeScalarToDecibels
kDevicePropertyVolumeDecibelsToScalar                            :: CA.kDevicePropertyVolumeDecibelsToScalar
kDevicePropertyStereoPan                                         :: CA.kDevicePropertyStereoPan
kDevicePropertyStereoPanChannels                                 :: CA.kDevicePropertyStereoPanChannels
kDevicePropertyMute                                              :: CA.kDevicePropertyMute
kDevicePropertySolo                                              :: CA.kDevicePropertySolo
kDevicePropertyPhantomPower                                      :: CA.kDevicePropertyPhantomPower
kDevicePropertyPhaseInvert                                       :: CA.kDevicePropertyPhaseInvert
kDevicePropertyClipLight                                         :: CA.kDevicePropertyClipLight
kDevicePropertyTalkback                                          :: CA.kDevicePropertyTalkback
kDevicePropertyListenback                                        :: CA.kDevicePropertyListenback
kDevicePropertyDataSource                                        :: CA.kDevicePropertyDataSource
kDevicePropertyDataSources                                       :: CA.kDevicePropertyDataSources
kDevicePropertyDataSourceNameForIDCFString                       :: CA.kDevicePropertyDataSourceNameForIDCFString
kDevicePropertyDataSourceKindForID                               :: CA.kDevicePropertyDataSourceKindForID
kDevicePropertyClockSource                                       :: CA.kDevicePropertyClockSource
kDevicePropertyClockSources                                      :: CA.kDevicePropertyClockSources
kDevicePropertyClockSourceNameForIDCFString                      :: CA.kDevicePropertyClockSourceNameForIDCFString
kDevicePropertyClockSourceKindForID                              :: CA.kDevicePropertyClockSourceKindForID
kDevicePropertyPlayThru                                          :: CA.kDevicePropertyPlayThru
kDevicePropertyPlayThruSolo                                      :: CA.kDevicePropertyPlayThruSolo
kDevicePropertyPlayThruVolumeScalar                              :: CA.kDevicePropertyPlayThruVolumeScalar
kDevicePropertyPlayThruVolumeDecibels                            :: CA.kDevicePropertyPlayThruVolumeDecibels
kDevicePropertyPlayThruVolumeRangeDecibels                       :: CA.kDevicePropertyPlayThruVolumeRangeDecibels
kDevicePropertyPlayThruVolumeScalarToDecibels                    :: CA.kDevicePropertyPlayThruVolumeScalarToDecibels
kDevicePropertyPlayThruVolumeDecibelsToScalar                    :: CA.kDevicePropertyPlayThruVolumeDecibelsToScalar
kDevicePropertyPlayThruStereoPan                                 :: CA.kDevicePropertyPlayThruStereoPan
kDevicePropertyPlayThruStereoPanChannels                         :: CA.kDevicePropertyPlayThruStereoPanChannels
kDevicePropertyPlayThruDestination                               :: CA.kDevicePropertyPlayThruDestination
kDevicePropertyPlayThruDestinations                              :: CA.kDevicePropertyPlayThruDestinations
kDevicePropertyPlayThruDestinationNameForIDCFString              :: CA.kDevicePropertyPlayThruDestinationNameForIDCFString
kDevicePropertyChannelNominalLineLevel                           :: CA.kDevicePropertyChannelNominalLineLevel
kDevicePropertyChannelNominalLineLevels                          :: CA.kDevicePropertyChannelNominalLineLevels
kDevicePropertyChannelNominalLineLevelNameForIDCFString          :: CA.kDevicePropertyChannelNominalLineLevelNameForIDCFString
kDevicePropertyHighPassFilterSetting                             :: CA.kDevicePropertyHighPassFilterSetting
kDevicePropertyHighPassFilterSettings                            :: CA.kDevicePropertyHighPassFilterSettings
kDevicePropertyHighPassFilterSettingNameForIDCFString            :: CA.kDevicePropertyHighPassFilterSettingNameForIDCFString
kDevicePropertySubVolumeScalar                                   :: CA.kDevicePropertySubVolumeScalar
kDevicePropertySubVolumeDecibels                                 :: CA.kDevicePropertySubVolumeDecibels
kDevicePropertySubVolumeRangeDecibels                            :: CA.kDevicePropertySubVolumeRangeDecibels
kDevicePropertySubVolumeScalarToDecibels                         :: CA.kDevicePropertySubVolumeScalarToDecibels
kDevicePropertySubVolumeDecibelsToScalar                         :: CA.kDevicePropertySubVolumeDecibelsToScalar
kDevicePropertySubMute                                           :: CA.kDevicePropertySubMute
kDevicePropertyVoiceActivityDetectionEnable                      :: CA.kDevicePropertyVoiceActivityDetectionEnable
kDevicePropertyVoiceActivityDetectionState                       :: CA.kDevicePropertyVoiceActivityDetectionState
kAggregateDeviceClassID                                          :: CA.kAggregateDeviceClassID
kAggregateDevicePropertyFullSubDeviceList                        :: CA.kAggregateDevicePropertyFullSubDeviceList
kAggregateDevicePropertyActiveSubDeviceList                      :: CA.kAggregateDevicePropertyActiveSubDeviceList
kAggregateDevicePropertyComposition                              :: CA.kAggregateDevicePropertyComposition
kAggregateDevicePropertyMainSubDevice                            :: CA.kAggregateDevicePropertyMainSubDevice
kAggregateDevicePropertyClockDevice                              :: CA.kAggregateDevicePropertyClockDevice
kAggregateDevicePropertyTapList                                  :: CA.kAggregateDevicePropertyTapList
kAggregateDevicePropertySubTapList                               :: CA.kAggregateDevicePropertySubTapList
kAggregateDriftCompensationMinQuality                            :: CA.kAggregateDriftCompensationMinQuality
kAggregateDriftCompensationLowQuality                            :: CA.kAggregateDriftCompensationLowQuality
kAggregateDriftCompensationMediumQuality                         :: CA.kAggregateDriftCompensationMediumQuality
kAggregateDriftCompensationHighQuality                           :: CA.kAggregateDriftCompensationHighQuality
kAggregateDriftCompensationMaxQuality                            :: CA.kAggregateDriftCompensationMaxQuality
kSubDeviceClassID                                                :: CA.kSubDeviceClassID
kSubDeviceDriftCompensationMinQuality                            :: CA.kSubDeviceDriftCompensationMinQuality
kSubDeviceDriftCompensationLowQuality                            :: CA.kSubDeviceDriftCompensationLowQuality
kSubDeviceDriftCompensationMediumQuality                         :: CA.kSubDeviceDriftCompensationMediumQuality
kSubDeviceDriftCompensationHighQuality                           :: CA.kSubDeviceDriftCompensationHighQuality
kSubDeviceDriftCompensationMaxQuality                            :: CA.kSubDeviceDriftCompensationMaxQuality
kSubDevicePropertyExtraLatency                                   :: CA.kSubDevicePropertyExtraLatency
kSubDevicePropertyDriftCompensation                              :: CA.kSubDevicePropertyDriftCompensation
kSubDevicePropertyDriftCompensationQuality                       :: CA.kSubDevicePropertyDriftCompensationQuality
kSubTapClassID                                                   :: CA.kSubTapClassID
kSubTapPropertyExtraLatency                                      :: CA.kSubTapPropertyExtraLatency
kSubTapPropertyDriftCompensation                                 :: CA.kSubTapPropertyDriftCompensation
kSubTapPropertyDriftCompensationQuality                          :: CA.kSubTapPropertyDriftCompensationQuality
kProcessClassID                                                  :: CA.kProcessClassID
kProcessPropertyPID                                              :: CA.kProcessPropertyPID
kProcessPropertyBundleID                                         :: CA.kProcessPropertyBundleID
kProcessPropertyDevices                                          :: CA.kProcessPropertyDevices
kProcessPropertyIsRunning                                        :: CA.kProcessPropertyIsRunning
kProcessPropertyIsRunningInput                                   :: CA.kProcessPropertyIsRunningInput
kProcessPropertyIsRunningOutput                                  :: CA.kProcessPropertyIsRunningOutput
kTapClassID                                                      :: CA.kTapClassID
kTapPropertyUID                                                  :: CA.kTapPropertyUID
kTapPropertyDescription                                          :: CA.kTapPropertyDescription
kTapPropertyFormat                                               :: CA.kTapPropertyFormat
kDevicePropertyScopeInput                                        :: CA.kDevicePropertyScopeInput
kDevicePropertyScopeOutput                                       :: CA.kDevicePropertyScopeOutput
kDevicePropertyScopePlayThrough                                  :: CA.kDevicePropertyScopePlayThrough
kPropertyWildcardPropertyID                                      :: CA.kPropertyWildcardPropertyID
kPropertyWildcardSection                                         :: CA.kPropertyWildcardSection
kPropertyWildcardChannel                                         :: CA.kPropertyWildcardChannel
kISubOwnerControlClassID                                         :: CA.kISubOwnerControlClassID
kLevelControlPropertyDecibelsToScalarTransferFunction            :: CA.kLevelControlPropertyDecibelsToScalarTransferFunction
kHardwarePropertyRunLoop                                         :: CA.kHardwarePropertyRunLoop
kHardwarePropertyDeviceForUID                                    :: CA.kHardwarePropertyDeviceForUID
kHardwarePropertyPlugInForBundleID                               :: CA.kHardwarePropertyPlugInForBundleID
kHardwarePropertyProcessIsMaster                                 :: CA.kHardwarePropertyProcessIsMaster
kHardwarePropertyBootChimeVolumeScalar                           :: CA.kHardwarePropertyBootChimeVolumeScalar
kHardwarePropertyBootChimeVolumeDecibels                         :: CA.kHardwarePropertyBootChimeVolumeDecibels
kHardwarePropertyBootChimeVolumeRangeDecibels                    :: CA.kHardwarePropertyBootChimeVolumeRangeDecibels
kHardwarePropertyBootChimeVolumeScalarToDecibels                 :: CA.kHardwarePropertyBootChimeVolumeScalarToDecibels
kHardwarePropertyBootChimeVolumeDecibelsToScalar                 :: CA.kHardwarePropertyBootChimeVolumeDecibelsToScalar
kHardwarePropertyBootChimeVolumeDecibelsToScalarTransferFunction :: CA.kHardwarePropertyBootChimeVolumeDecibelsToScalarTransferFunction
kDeviceUnknown                                                   :: CA.kDeviceUnknown
kDeviceTransportTypeAutoAggregate                                :: CA.kDeviceTransportTypeAutoAggregate
kDevicePropertyVolumeDecibelsToScalarTransferFunction            :: CA.kDevicePropertyVolumeDecibelsToScalarTransferFunction
kDevicePropertyPlayThruVolumeDecibelsToScalarTransferFunction    :: CA.kDevicePropertyPlayThruVolumeDecibelsToScalarTransferFunction
kDevicePropertyDriverShouldOwniSub                               :: CA.kDevicePropertyDriverShouldOwniSub
kDevicePropertySubVolumeDecibelsToScalarTransferFunction         :: CA.kDevicePropertySubVolumeDecibelsToScalarTransferFunction
kDevicePropertyDeviceName                                        :: CA.kDevicePropertyDeviceName
kDevicePropertyDeviceNameCFString                                :: CA.kDevicePropertyDeviceNameCFString
kDevicePropertyDeviceManufacturer                                :: CA.kDevicePropertyDeviceManufacturer
kDevicePropertyDeviceManufacturerCFString                        :: CA.kDevicePropertyDeviceManufacturerCFString
kDevicePropertyRegisterBufferList                                :: CA.kDevicePropertyRegisterBufferList
kDevicePropertyBufferSize                                        :: CA.kDevicePropertyBufferSize
kDevicePropertyBufferSizeRange                                   :: CA.kDevicePropertyBufferSizeRange
kDevicePropertyChannelName                                       :: CA.kDevicePropertyChannelName
kDevicePropertyChannelNameCFString                               :: CA.kDevicePropertyChannelNameCFString
kDevicePropertyChannelCategoryName                               :: CA.kDevicePropertyChannelCategoryName
kDevicePropertyChannelCategoryNameCFString                       :: CA.kDevicePropertyChannelCategoryNameCFString
kDevicePropertyChannelNumberName                                 :: CA.kDevicePropertyChannelNumberName
kDevicePropertyChannelNumberNameCFString                         :: CA.kDevicePropertyChannelNumberNameCFString
kDevicePropertySupportsMixing                                    :: CA.kDevicePropertySupportsMixing
kDevicePropertyStreamFormat                                      :: CA.kDevicePropertyStreamFormat
kDevicePropertyStreamFormats                                     :: CA.kDevicePropertyStreamFormats
kDevicePropertyStreamFormatSupported                             :: CA.kDevicePropertyStreamFormatSupported
kDevicePropertyStreamFormatMatch                                 :: CA.kDevicePropertyStreamFormatMatch
kDevicePropertyDataSourceNameForID                               :: CA.kDevicePropertyDataSourceNameForID
kDevicePropertyClockSourceNameForID                              :: CA.kDevicePropertyClockSourceNameForID
kDevicePropertyPlayThruDestinationNameForID                      :: CA.kDevicePropertyPlayThruDestinationNameForID
kDevicePropertyChannelNominalLineLevelNameForID                  :: CA.kDevicePropertyChannelNominalLineLevelNameForID
kDevicePropertyHighPassFilterSettingNameForID                    :: CA.kDevicePropertyHighPassFilterSettingNameForID
kAggregateDevicePropertyMasterSubDevice                          :: CA.kAggregateDevicePropertyMasterSubDevice
kStreamUnknown                                                   :: CA.kStreamUnknown
kStreamPropertyOwningDevice                                      :: CA.kStreamPropertyOwningDevice
kStreamPropertyPhysicalFormats                                   :: CA.kStreamPropertyPhysicalFormats
kStreamPropertyPhysicalFormatSupported                           :: CA.kStreamPropertyPhysicalFormatSupported
kStreamPropertyPhysicalFormatMatch                               :: CA.kStreamPropertyPhysicalFormatMatch
kBootChimeVolumeControlClassID                                   :: CA.kBootChimeVolumeControlClassID
kControlPropertyVariant                                          :: CA.kControlPropertyVariant
kClockSourceControlPropertyItemKind                              :: CA.kClockSourceControlPropertyItemKind
kStreamAnyRate                                                   :: CA.kStreamAnyRate

